### ISSUE TITLE
VirtualWindowShare.cs could not be found

### ISSUE THREAD

**Issue by shravyav1991** [Vidyo/vidyo.io-connector-xamarin#17]
After building the project I get this error:

'C:\Users\name\Desktop\vidyo.io-connector-xamarin-master\vidyo.io-connector-xamarin-master\VidyoConnector.Android\..\VidyoClient-AndroidSDK\include\csharp\VirtualWindowShare.cs' could not be found.	

Same error appears in both android and iOS sdk.

'C:\Users\name\Desktop\vidyo.io-connector-xamarin-master\vidyo.io-connector-xamarin-master\VidyoConnector.iOS\..\VidyoClient-iOSSDK\include\csharp\VirtualWindowShare.cs' could not be found.	VidyoConnector.iOS

**Comment by tmelko-vidyo** [comment]
Hi,
Repo has been updated in order to support 19.2.0.8 VidyoClient SDK. We have some changes to the API and this file is outdated. Linking was fixed. Please pull the changes and try over again.
