### ISSUE TITLE
Get audio but not video

### ISSUE THREAD

**Issue by jvillaro** [Vidyo/vidyo.io-connector-xamarin#21]
Hi, 

I just downloaded and tested this demo on Android (and the web demo on the Vidyo site)  but I have an issue with the video.
I can chat with voice but I get no video, I can´t see ant video preview of my camera and I can´t see anything from the other participant in the chatroom.

Am I missing something here? Is this normal for the demo? Or is there an error?

Thanks in advance

**Comment by tmelko-vidyo** [comment]
Seems like you are missing the camera permissions. Starting from the Android 23 SDK version you have to request permissions in runtime: https://developer.android.com/training/permissions/requesting
Unfortunately, this sample has no request permission logic implemented. Alternatively, you can grant permissions in app info settings as for the demo purpose and do not bother with the runtime request.

**Comment by jvillaro** [comment]
Hi, I´ll have to check again I think I saw or added the permission.
Thanks for your response, I´ll check it out and report back
