### ISSUE TITLE
Not Getting Video 

### ISSUE THREAD

**Issue by ashokBRjangir** [Vidyo/vidyo.io-connector-xamarin#22]
I tested this demo on Xamarin Forms , When i calling Video call page as Main page from App.xaml.cs it's working fine but when i try to call Video call page from another page of app then page showing blank.
![Working](https://user-images.githubusercontent.com/50617438/72509751-34b42280-386e-11ea-8e9f-8dd1d1921dbb.png)
![NotWorking](https://user-images.githubusercontent.com/50617438/72509761-3c73c700-386e-11ea-9f88-08b9dd8eeccc.png)

**Comment by tmelko-vidyo** [comment]
Please check out this sample for handling navigation:
https://github.com/tmelko-vidyo/vidyo-io-connector-xamarin-navigation
